URL_SERVICE = "https://e86df996-964d-42c5-988a-66c547b4a62d.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_USER_PATH = "/api/v1/users/"
